stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  LOGIN: raizero42

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run -d -p 6000:6000 --name registry registry:2
    - docker run --name postgres -e POSTGRES_DB=elstation -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=root -p 5432:5432 -d postgres:16
    - docker network create my_network
    - docker network connect my_network postgres
    - docker run -p 8080:80 --name pgadmin --network my_network -e 'PGADMIN_DEFAULT_EMAIL=admin@example.com' -e 'PGADMIN_DEFAULT_PASSWORD=admin' -d dpage/pgadmin4
    - docker build -t client ./client
    - docker build -t server ./server
    - docker tag server:latest $LOGIN/server:latest
    - docker tag server:latest $LOGIN/client:latest
    - docker login $LOGIN
    # Пуш в реестр GitLab
    - docker push $LOGIN/client:latest
    - docker push $LOGIN/server:latest

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    # Логин в реестр
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}

    # Запуск docker-compose
    - docker-compose -f docker-compose.infrastructure.yml up -d
